#pragma kernel CSMain

uniform int _VolumeSize;

RWTexture3D<float4> _VolumeTexture;
StructuredBuffer<float4> _VoxelBuffer;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint idx = id.x + id.y * _VolumeSize + id.z * _VolumeSize * _VolumeSize; 	
	//convert data
	float4 val4 = _VoxelBuffer[idx];
	_VolumeTexture[id] = val4;
//	_VolumeTexture[id] = float4(_VoxelBuffer[idx].x / 1000.0f,_NormalBuffer1[idx] / 1000.0f,_NormalBuffer2[idx] / 1000.0f,_NormalBuffer3[idx] / 1000.0f);
}
