#pragma kernel CSMain

uniform int _VolumeSize;

RWTexture3D<float> _VolumeTexture;
StructuredBuffer<int> _VoxelBuffer;


// Unpacks a uint to a float2
float2 uintTofloat2(uint uValue)
{
	return float2(f16tof32(uValue), f16tof32(uValue >> 16));
}

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint idx = id.x + id.y * _VolumeSize + id.z * _VolumeSize * _VolumeSize; 	
	//convert data
	_VolumeTexture[id] = uintTofloat2(_VoxelBuffer[idx]).x;
}
