#pragma kernel CSMain

uniform int _VolumeSize;
RWStructuredBuffer<int4> _VoxelBuffer;
RWBuffer<uint> _VoxelFlagBuffer;


uint float2Touint(float2 f2Value)
{
	return (f32tof16(f2Value.x) + (f32tof16(f2Value.y) << 16));
}

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint idx = id.x + id.y * _VolumeSize + id.z * _VolumeSize * _VolumeSize; 
//	_VoxelBuffer[idx] = float2Touint(-99999.9f,1.0f);  
	_VoxelBuffer[idx] = int4(-9999999,1000,0,0);   
	_VoxelFlagBuffer[idx]=0; 
}
